/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tenx.resi.ms.contract.api.message.offer;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PartyMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9032224091482245912L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PartyMessage\",\"namespace\":\"com.tenx.resi.ms.contract.api.message.offer\",\"fields\":[{\"name\":\"partyId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"partyType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"participantType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"firstName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"lastName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"middleName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"noMiddleName\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"dob\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"companyName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"addressType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"streetNumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"streetName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"streetUnit\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"city\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"state\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"postalCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"emailAddress\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"phoneType\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"phoneNumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"licenseNumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"licenseState\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"licenseType\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PartyMessage> ENCODER =
      new BinaryMessageEncoder<PartyMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PartyMessage> DECODER =
      new BinaryMessageDecoder<PartyMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PartyMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PartyMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PartyMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PartyMessage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PartyMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PartyMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PartyMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PartyMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long partyId;
   private java.lang.CharSequence partyType;
   private java.lang.CharSequence participantType;
   private java.lang.CharSequence firstName;
   private java.lang.CharSequence lastName;
   private java.lang.CharSequence middleName;
   private java.lang.Boolean noMiddleName;
   private java.lang.CharSequence dob;
   private java.lang.CharSequence companyName;
   private java.lang.CharSequence addressType;
   private java.lang.CharSequence streetNumber;
   private java.lang.CharSequence streetName;
   private java.lang.CharSequence streetUnit;
   private java.lang.CharSequence city;
   private java.lang.CharSequence state;
   private java.lang.CharSequence postalCode;
   private java.lang.CharSequence emailAddress;
   private java.lang.CharSequence phoneType;
   private java.lang.CharSequence phoneNumber;
   private java.lang.CharSequence licenseNumber;
   private java.lang.CharSequence licenseState;
   private java.lang.CharSequence licenseType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PartyMessage() {}

  /**
   * All-args constructor.
   * @param partyId The new value for partyId
   * @param partyType The new value for partyType
   * @param participantType The new value for participantType
   * @param firstName The new value for firstName
   * @param lastName The new value for lastName
   * @param middleName The new value for middleName
   * @param noMiddleName The new value for noMiddleName
   * @param dob The new value for dob
   * @param companyName The new value for companyName
   * @param addressType The new value for addressType
   * @param streetNumber The new value for streetNumber
   * @param streetName The new value for streetName
   * @param streetUnit The new value for streetUnit
   * @param city The new value for city
   * @param state The new value for state
   * @param postalCode The new value for postalCode
   * @param emailAddress The new value for emailAddress
   * @param phoneType The new value for phoneType
   * @param phoneNumber The new value for phoneNumber
   * @param licenseNumber The new value for licenseNumber
   * @param licenseState The new value for licenseState
   * @param licenseType The new value for licenseType
   */
  public PartyMessage(java.lang.Long partyId, java.lang.CharSequence partyType, java.lang.CharSequence participantType, java.lang.CharSequence firstName, java.lang.CharSequence lastName, java.lang.CharSequence middleName, java.lang.Boolean noMiddleName, java.lang.CharSequence dob, java.lang.CharSequence companyName, java.lang.CharSequence addressType, java.lang.CharSequence streetNumber, java.lang.CharSequence streetName, java.lang.CharSequence streetUnit, java.lang.CharSequence city, java.lang.CharSequence state, java.lang.CharSequence postalCode, java.lang.CharSequence emailAddress, java.lang.CharSequence phoneType, java.lang.CharSequence phoneNumber, java.lang.CharSequence licenseNumber, java.lang.CharSequence licenseState, java.lang.CharSequence licenseType) {
    this.partyId = partyId;
    this.partyType = partyType;
    this.participantType = participantType;
    this.firstName = firstName;
    this.lastName = lastName;
    this.middleName = middleName;
    this.noMiddleName = noMiddleName;
    this.dob = dob;
    this.companyName = companyName;
    this.addressType = addressType;
    this.streetNumber = streetNumber;
    this.streetName = streetName;
    this.streetUnit = streetUnit;
    this.city = city;
    this.state = state;
    this.postalCode = postalCode;
    this.emailAddress = emailAddress;
    this.phoneType = phoneType;
    this.phoneNumber = phoneNumber;
    this.licenseNumber = licenseNumber;
    this.licenseState = licenseState;
    this.licenseType = licenseType;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return partyId;
    case 1: return partyType;
    case 2: return participantType;
    case 3: return firstName;
    case 4: return lastName;
    case 5: return middleName;
    case 6: return noMiddleName;
    case 7: return dob;
    case 8: return companyName;
    case 9: return addressType;
    case 10: return streetNumber;
    case 11: return streetName;
    case 12: return streetUnit;
    case 13: return city;
    case 14: return state;
    case 15: return postalCode;
    case 16: return emailAddress;
    case 17: return phoneType;
    case 18: return phoneNumber;
    case 19: return licenseNumber;
    case 20: return licenseState;
    case 21: return licenseType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: partyId = (java.lang.Long)value$; break;
    case 1: partyType = (java.lang.CharSequence)value$; break;
    case 2: participantType = (java.lang.CharSequence)value$; break;
    case 3: firstName = (java.lang.CharSequence)value$; break;
    case 4: lastName = (java.lang.CharSequence)value$; break;
    case 5: middleName = (java.lang.CharSequence)value$; break;
    case 6: noMiddleName = (java.lang.Boolean)value$; break;
    case 7: dob = (java.lang.CharSequence)value$; break;
    case 8: companyName = (java.lang.CharSequence)value$; break;
    case 9: addressType = (java.lang.CharSequence)value$; break;
    case 10: streetNumber = (java.lang.CharSequence)value$; break;
    case 11: streetName = (java.lang.CharSequence)value$; break;
    case 12: streetUnit = (java.lang.CharSequence)value$; break;
    case 13: city = (java.lang.CharSequence)value$; break;
    case 14: state = (java.lang.CharSequence)value$; break;
    case 15: postalCode = (java.lang.CharSequence)value$; break;
    case 16: emailAddress = (java.lang.CharSequence)value$; break;
    case 17: phoneType = (java.lang.CharSequence)value$; break;
    case 18: phoneNumber = (java.lang.CharSequence)value$; break;
    case 19: licenseNumber = (java.lang.CharSequence)value$; break;
    case 20: licenseState = (java.lang.CharSequence)value$; break;
    case 21: licenseType = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'partyId' field.
   * @return The value of the 'partyId' field.
   */
  public java.lang.Long getPartyId() {
    return partyId;
  }


  /**
   * Sets the value of the 'partyId' field.
   * @param value the value to set.
   */
  public void setPartyId(java.lang.Long value) {
    this.partyId = value;
  }

  /**
   * Gets the value of the 'partyType' field.
   * @return The value of the 'partyType' field.
   */
  public java.lang.CharSequence getPartyType() {
    return partyType;
  }


  /**
   * Sets the value of the 'partyType' field.
   * @param value the value to set.
   */
  public void setPartyType(java.lang.CharSequence value) {
    this.partyType = value;
  }

  /**
   * Gets the value of the 'participantType' field.
   * @return The value of the 'participantType' field.
   */
  public java.lang.CharSequence getParticipantType() {
    return participantType;
  }


  /**
   * Sets the value of the 'participantType' field.
   * @param value the value to set.
   */
  public void setParticipantType(java.lang.CharSequence value) {
    this.participantType = value;
  }

  /**
   * Gets the value of the 'firstName' field.
   * @return The value of the 'firstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return firstName;
  }


  /**
   * Sets the value of the 'firstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.firstName = value;
  }

  /**
   * Gets the value of the 'lastName' field.
   * @return The value of the 'lastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return lastName;
  }


  /**
   * Sets the value of the 'lastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the 'middleName' field.
   * @return The value of the 'middleName' field.
   */
  public java.lang.CharSequence getMiddleName() {
    return middleName;
  }


  /**
   * Sets the value of the 'middleName' field.
   * @param value the value to set.
   */
  public void setMiddleName(java.lang.CharSequence value) {
    this.middleName = value;
  }

  /**
   * Gets the value of the 'noMiddleName' field.
   * @return The value of the 'noMiddleName' field.
   */
  public java.lang.Boolean getNoMiddleName() {
    return noMiddleName;
  }


  /**
   * Sets the value of the 'noMiddleName' field.
   * @param value the value to set.
   */
  public void setNoMiddleName(java.lang.Boolean value) {
    this.noMiddleName = value;
  }

  /**
   * Gets the value of the 'dob' field.
   * @return The value of the 'dob' field.
   */
  public java.lang.CharSequence getDob() {
    return dob;
  }


  /**
   * Sets the value of the 'dob' field.
   * @param value the value to set.
   */
  public void setDob(java.lang.CharSequence value) {
    this.dob = value;
  }

  /**
   * Gets the value of the 'companyName' field.
   * @return The value of the 'companyName' field.
   */
  public java.lang.CharSequence getCompanyName() {
    return companyName;
  }


  /**
   * Sets the value of the 'companyName' field.
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.CharSequence value) {
    this.companyName = value;
  }

  /**
   * Gets the value of the 'addressType' field.
   * @return The value of the 'addressType' field.
   */
  public java.lang.CharSequence getAddressType() {
    return addressType;
  }


  /**
   * Sets the value of the 'addressType' field.
   * @param value the value to set.
   */
  public void setAddressType(java.lang.CharSequence value) {
    this.addressType = value;
  }

  /**
   * Gets the value of the 'streetNumber' field.
   * @return The value of the 'streetNumber' field.
   */
  public java.lang.CharSequence getStreetNumber() {
    return streetNumber;
  }


  /**
   * Sets the value of the 'streetNumber' field.
   * @param value the value to set.
   */
  public void setStreetNumber(java.lang.CharSequence value) {
    this.streetNumber = value;
  }

  /**
   * Gets the value of the 'streetName' field.
   * @return The value of the 'streetName' field.
   */
  public java.lang.CharSequence getStreetName() {
    return streetName;
  }


  /**
   * Sets the value of the 'streetName' field.
   * @param value the value to set.
   */
  public void setStreetName(java.lang.CharSequence value) {
    this.streetName = value;
  }

  /**
   * Gets the value of the 'streetUnit' field.
   * @return The value of the 'streetUnit' field.
   */
  public java.lang.CharSequence getStreetUnit() {
    return streetUnit;
  }


  /**
   * Sets the value of the 'streetUnit' field.
   * @param value the value to set.
   */
  public void setStreetUnit(java.lang.CharSequence value) {
    this.streetUnit = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.CharSequence getState() {
    return state;
  }


  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.CharSequence value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'postalCode' field.
   * @return The value of the 'postalCode' field.
   */
  public java.lang.CharSequence getPostalCode() {
    return postalCode;
  }


  /**
   * Sets the value of the 'postalCode' field.
   * @param value the value to set.
   */
  public void setPostalCode(java.lang.CharSequence value) {
    this.postalCode = value;
  }

  /**
   * Gets the value of the 'emailAddress' field.
   * @return The value of the 'emailAddress' field.
   */
  public java.lang.CharSequence getEmailAddress() {
    return emailAddress;
  }


  /**
   * Sets the value of the 'emailAddress' field.
   * @param value the value to set.
   */
  public void setEmailAddress(java.lang.CharSequence value) {
    this.emailAddress = value;
  }

  /**
   * Gets the value of the 'phoneType' field.
   * @return The value of the 'phoneType' field.
   */
  public java.lang.CharSequence getPhoneType() {
    return phoneType;
  }


  /**
   * Sets the value of the 'phoneType' field.
   * @param value the value to set.
   */
  public void setPhoneType(java.lang.CharSequence value) {
    this.phoneType = value;
  }

  /**
   * Gets the value of the 'phoneNumber' field.
   * @return The value of the 'phoneNumber' field.
   */
  public java.lang.CharSequence getPhoneNumber() {
    return phoneNumber;
  }


  /**
   * Sets the value of the 'phoneNumber' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.CharSequence value) {
    this.phoneNumber = value;
  }

  /**
   * Gets the value of the 'licenseNumber' field.
   * @return The value of the 'licenseNumber' field.
   */
  public java.lang.CharSequence getLicenseNumber() {
    return licenseNumber;
  }


  /**
   * Sets the value of the 'licenseNumber' field.
   * @param value the value to set.
   */
  public void setLicenseNumber(java.lang.CharSequence value) {
    this.licenseNumber = value;
  }

  /**
   * Gets the value of the 'licenseState' field.
   * @return The value of the 'licenseState' field.
   */
  public java.lang.CharSequence getLicenseState() {
    return licenseState;
  }


  /**
   * Sets the value of the 'licenseState' field.
   * @param value the value to set.
   */
  public void setLicenseState(java.lang.CharSequence value) {
    this.licenseState = value;
  }

  /**
   * Gets the value of the 'licenseType' field.
   * @return The value of the 'licenseType' field.
   */
  public java.lang.CharSequence getLicenseType() {
    return licenseType;
  }


  /**
   * Sets the value of the 'licenseType' field.
   * @param value the value to set.
   */
  public void setLicenseType(java.lang.CharSequence value) {
    this.licenseType = value;
  }

  /**
   * Creates a new PartyMessage RecordBuilder.
   * @return A new PartyMessage RecordBuilder
   */
  public static com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder newBuilder() {
    return new com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder();
  }

  /**
   * Creates a new PartyMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PartyMessage RecordBuilder
   */
  public static com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder newBuilder(com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder other) {
    if (other == null) {
      return new com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder();
    } else {
      return new com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder(other);
    }
  }

  /**
   * Creates a new PartyMessage RecordBuilder by copying an existing PartyMessage instance.
   * @param other The existing instance to copy.
   * @return A new PartyMessage RecordBuilder
   */
  public static com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder newBuilder(com.tenx.resi.ms.contract.api.message.offer.PartyMessage other) {
    if (other == null) {
      return new com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder();
    } else {
      return new com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for PartyMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PartyMessage>
    implements org.apache.avro.data.RecordBuilder<PartyMessage> {

    private java.lang.Long partyId;
    private java.lang.CharSequence partyType;
    private java.lang.CharSequence participantType;
    private java.lang.CharSequence firstName;
    private java.lang.CharSequence lastName;
    private java.lang.CharSequence middleName;
    private java.lang.Boolean noMiddleName;
    private java.lang.CharSequence dob;
    private java.lang.CharSequence companyName;
    private java.lang.CharSequence addressType;
    private java.lang.CharSequence streetNumber;
    private java.lang.CharSequence streetName;
    private java.lang.CharSequence streetUnit;
    private java.lang.CharSequence city;
    private java.lang.CharSequence state;
    private java.lang.CharSequence postalCode;
    private java.lang.CharSequence emailAddress;
    private java.lang.CharSequence phoneType;
    private java.lang.CharSequence phoneNumber;
    private java.lang.CharSequence licenseNumber;
    private java.lang.CharSequence licenseState;
    private java.lang.CharSequence licenseType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.partyId)) {
        this.partyId = data().deepCopy(fields()[0].schema(), other.partyId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.partyType)) {
        this.partyType = data().deepCopy(fields()[1].schema(), other.partyType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.participantType)) {
        this.participantType = data().deepCopy(fields()[2].schema(), other.participantType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.firstName)) {
        this.firstName = data().deepCopy(fields()[3].schema(), other.firstName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.lastName)) {
        this.lastName = data().deepCopy(fields()[4].schema(), other.lastName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.middleName)) {
        this.middleName = data().deepCopy(fields()[5].schema(), other.middleName);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.noMiddleName)) {
        this.noMiddleName = data().deepCopy(fields()[6].schema(), other.noMiddleName);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.dob)) {
        this.dob = data().deepCopy(fields()[7].schema(), other.dob);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.companyName)) {
        this.companyName = data().deepCopy(fields()[8].schema(), other.companyName);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.addressType)) {
        this.addressType = data().deepCopy(fields()[9].schema(), other.addressType);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.streetNumber)) {
        this.streetNumber = data().deepCopy(fields()[10].schema(), other.streetNumber);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.streetName)) {
        this.streetName = data().deepCopy(fields()[11].schema(), other.streetName);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.streetUnit)) {
        this.streetUnit = data().deepCopy(fields()[12].schema(), other.streetUnit);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.city)) {
        this.city = data().deepCopy(fields()[13].schema(), other.city);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.state)) {
        this.state = data().deepCopy(fields()[14].schema(), other.state);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[15].schema(), other.postalCode);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.emailAddress)) {
        this.emailAddress = data().deepCopy(fields()[16].schema(), other.emailAddress);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.phoneType)) {
        this.phoneType = data().deepCopy(fields()[17].schema(), other.phoneType);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[18].schema(), other.phoneNumber);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.licenseNumber)) {
        this.licenseNumber = data().deepCopy(fields()[19].schema(), other.licenseNumber);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.licenseState)) {
        this.licenseState = data().deepCopy(fields()[20].schema(), other.licenseState);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.licenseType)) {
        this.licenseType = data().deepCopy(fields()[21].schema(), other.licenseType);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
    }

    /**
     * Creates a Builder by copying an existing PartyMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tenx.resi.ms.contract.api.message.offer.PartyMessage other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.partyId)) {
        this.partyId = data().deepCopy(fields()[0].schema(), other.partyId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.partyType)) {
        this.partyType = data().deepCopy(fields()[1].schema(), other.partyType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.participantType)) {
        this.participantType = data().deepCopy(fields()[2].schema(), other.participantType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.firstName)) {
        this.firstName = data().deepCopy(fields()[3].schema(), other.firstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.lastName)) {
        this.lastName = data().deepCopy(fields()[4].schema(), other.lastName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.middleName)) {
        this.middleName = data().deepCopy(fields()[5].schema(), other.middleName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.noMiddleName)) {
        this.noMiddleName = data().deepCopy(fields()[6].schema(), other.noMiddleName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.dob)) {
        this.dob = data().deepCopy(fields()[7].schema(), other.dob);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.companyName)) {
        this.companyName = data().deepCopy(fields()[8].schema(), other.companyName);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.addressType)) {
        this.addressType = data().deepCopy(fields()[9].schema(), other.addressType);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.streetNumber)) {
        this.streetNumber = data().deepCopy(fields()[10].schema(), other.streetNumber);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.streetName)) {
        this.streetName = data().deepCopy(fields()[11].schema(), other.streetName);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.streetUnit)) {
        this.streetUnit = data().deepCopy(fields()[12].schema(), other.streetUnit);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.city)) {
        this.city = data().deepCopy(fields()[13].schema(), other.city);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.state)) {
        this.state = data().deepCopy(fields()[14].schema(), other.state);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[15].schema(), other.postalCode);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.emailAddress)) {
        this.emailAddress = data().deepCopy(fields()[16].schema(), other.emailAddress);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.phoneType)) {
        this.phoneType = data().deepCopy(fields()[17].schema(), other.phoneType);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.phoneNumber)) {
        this.phoneNumber = data().deepCopy(fields()[18].schema(), other.phoneNumber);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.licenseNumber)) {
        this.licenseNumber = data().deepCopy(fields()[19].schema(), other.licenseNumber);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.licenseState)) {
        this.licenseState = data().deepCopy(fields()[20].schema(), other.licenseState);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.licenseType)) {
        this.licenseType = data().deepCopy(fields()[21].schema(), other.licenseType);
        fieldSetFlags()[21] = true;
      }
    }

    /**
      * Gets the value of the 'partyId' field.
      * @return The value.
      */
    public java.lang.Long getPartyId() {
      return partyId;
    }


    /**
      * Sets the value of the 'partyId' field.
      * @param value The value of 'partyId'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setPartyId(java.lang.Long value) {
      validate(fields()[0], value);
      this.partyId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'partyId' field has been set.
      * @return True if the 'partyId' field has been set, false otherwise.
      */
    public boolean hasPartyId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'partyId' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearPartyId() {
      partyId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'partyType' field.
      * @return The value.
      */
    public java.lang.CharSequence getPartyType() {
      return partyType;
    }


    /**
      * Sets the value of the 'partyType' field.
      * @param value The value of 'partyType'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setPartyType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.partyType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'partyType' field has been set.
      * @return True if the 'partyType' field has been set, false otherwise.
      */
    public boolean hasPartyType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'partyType' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearPartyType() {
      partyType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'participantType' field.
      * @return The value.
      */
    public java.lang.CharSequence getParticipantType() {
      return participantType;
    }


    /**
      * Sets the value of the 'participantType' field.
      * @param value The value of 'participantType'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setParticipantType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.participantType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'participantType' field has been set.
      * @return True if the 'participantType' field has been set, false otherwise.
      */
    public boolean hasParticipantType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'participantType' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearParticipantType() {
      participantType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return firstName;
    }


    /**
      * Sets the value of the 'firstName' field.
      * @param value The value of 'firstName'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.firstName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'firstName' field has been set.
      * @return True if the 'firstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'firstName' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearFirstName() {
      firstName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return lastName;
    }


    /**
      * Sets the value of the 'lastName' field.
      * @param value The value of 'lastName'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.lastName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'lastName' field has been set.
      * @return True if the 'lastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'lastName' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearLastName() {
      lastName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'middleName' field.
      * @return The value.
      */
    public java.lang.CharSequence getMiddleName() {
      return middleName;
    }


    /**
      * Sets the value of the 'middleName' field.
      * @param value The value of 'middleName'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setMiddleName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.middleName = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'middleName' field has been set.
      * @return True if the 'middleName' field has been set, false otherwise.
      */
    public boolean hasMiddleName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'middleName' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearMiddleName() {
      middleName = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'noMiddleName' field.
      * @return The value.
      */
    public java.lang.Boolean getNoMiddleName() {
      return noMiddleName;
    }


    /**
      * Sets the value of the 'noMiddleName' field.
      * @param value The value of 'noMiddleName'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setNoMiddleName(java.lang.Boolean value) {
      validate(fields()[6], value);
      this.noMiddleName = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'noMiddleName' field has been set.
      * @return True if the 'noMiddleName' field has been set, false otherwise.
      */
    public boolean hasNoMiddleName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'noMiddleName' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearNoMiddleName() {
      noMiddleName = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'dob' field.
      * @return The value.
      */
    public java.lang.CharSequence getDob() {
      return dob;
    }


    /**
      * Sets the value of the 'dob' field.
      * @param value The value of 'dob'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setDob(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.dob = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'dob' field has been set.
      * @return True if the 'dob' field has been set, false otherwise.
      */
    public boolean hasDob() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'dob' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearDob() {
      dob = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyName() {
      return companyName;
    }


    /**
      * Sets the value of the 'companyName' field.
      * @param value The value of 'companyName'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setCompanyName(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.companyName = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'companyName' field has been set.
      * @return True if the 'companyName' field has been set, false otherwise.
      */
    public boolean hasCompanyName() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'companyName' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearCompanyName() {
      companyName = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'addressType' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressType() {
      return addressType;
    }


    /**
      * Sets the value of the 'addressType' field.
      * @param value The value of 'addressType'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setAddressType(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.addressType = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'addressType' field has been set.
      * @return True if the 'addressType' field has been set, false otherwise.
      */
    public boolean hasAddressType() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'addressType' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearAddressType() {
      addressType = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'streetNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreetNumber() {
      return streetNumber;
    }


    /**
      * Sets the value of the 'streetNumber' field.
      * @param value The value of 'streetNumber'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setStreetNumber(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.streetNumber = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'streetNumber' field has been set.
      * @return True if the 'streetNumber' field has been set, false otherwise.
      */
    public boolean hasStreetNumber() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'streetNumber' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearStreetNumber() {
      streetNumber = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'streetName' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreetName() {
      return streetName;
    }


    /**
      * Sets the value of the 'streetName' field.
      * @param value The value of 'streetName'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setStreetName(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.streetName = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'streetName' field has been set.
      * @return True if the 'streetName' field has been set, false otherwise.
      */
    public boolean hasStreetName() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'streetName' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearStreetName() {
      streetName = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'streetUnit' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreetUnit() {
      return streetUnit;
    }


    /**
      * Sets the value of the 'streetUnit' field.
      * @param value The value of 'streetUnit'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setStreetUnit(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.streetUnit = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'streetUnit' field has been set.
      * @return True if the 'streetUnit' field has been set, false otherwise.
      */
    public boolean hasStreetUnit() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'streetUnit' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearStreetUnit() {
      streetUnit = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.city = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearCity() {
      city = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.CharSequence getState() {
      return state;
    }


    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setState(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.state = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearState() {
      state = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'postalCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostalCode() {
      return postalCode;
    }


    /**
      * Sets the value of the 'postalCode' field.
      * @param value The value of 'postalCode'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setPostalCode(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.postalCode = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'postalCode' field has been set.
      * @return True if the 'postalCode' field has been set, false otherwise.
      */
    public boolean hasPostalCode() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'postalCode' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearPostalCode() {
      postalCode = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'emailAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmailAddress() {
      return emailAddress;
    }


    /**
      * Sets the value of the 'emailAddress' field.
      * @param value The value of 'emailAddress'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setEmailAddress(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.emailAddress = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'emailAddress' field has been set.
      * @return True if the 'emailAddress' field has been set, false otherwise.
      */
    public boolean hasEmailAddress() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'emailAddress' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearEmailAddress() {
      emailAddress = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'phoneType' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhoneType() {
      return phoneType;
    }


    /**
      * Sets the value of the 'phoneType' field.
      * @param value The value of 'phoneType'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setPhoneType(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.phoneType = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'phoneType' field has been set.
      * @return True if the 'phoneType' field has been set, false otherwise.
      */
    public boolean hasPhoneType() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'phoneType' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearPhoneType() {
      phoneType = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'phoneNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhoneNumber() {
      return phoneNumber;
    }


    /**
      * Sets the value of the 'phoneNumber' field.
      * @param value The value of 'phoneNumber'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setPhoneNumber(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.phoneNumber = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'phoneNumber' field has been set.
      * @return True if the 'phoneNumber' field has been set, false otherwise.
      */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'phoneNumber' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearPhoneNumber() {
      phoneNumber = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'licenseNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getLicenseNumber() {
      return licenseNumber;
    }


    /**
      * Sets the value of the 'licenseNumber' field.
      * @param value The value of 'licenseNumber'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setLicenseNumber(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.licenseNumber = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'licenseNumber' field has been set.
      * @return True if the 'licenseNumber' field has been set, false otherwise.
      */
    public boolean hasLicenseNumber() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'licenseNumber' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearLicenseNumber() {
      licenseNumber = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'licenseState' field.
      * @return The value.
      */
    public java.lang.CharSequence getLicenseState() {
      return licenseState;
    }


    /**
      * Sets the value of the 'licenseState' field.
      * @param value The value of 'licenseState'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setLicenseState(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.licenseState = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'licenseState' field has been set.
      * @return True if the 'licenseState' field has been set, false otherwise.
      */
    public boolean hasLicenseState() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'licenseState' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearLicenseState() {
      licenseState = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'licenseType' field.
      * @return The value.
      */
    public java.lang.CharSequence getLicenseType() {
      return licenseType;
    }


    /**
      * Sets the value of the 'licenseType' field.
      * @param value The value of 'licenseType'.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder setLicenseType(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.licenseType = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'licenseType' field has been set.
      * @return True if the 'licenseType' field has been set, false otherwise.
      */
    public boolean hasLicenseType() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'licenseType' field.
      * @return This builder.
      */
    public com.tenx.resi.ms.contract.api.message.offer.PartyMessage.Builder clearLicenseType() {
      licenseType = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PartyMessage build() {
      try {
        PartyMessage record = new PartyMessage();
        record.partyId = fieldSetFlags()[0] ? this.partyId : (java.lang.Long) defaultValue(fields()[0]);
        record.partyType = fieldSetFlags()[1] ? this.partyType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.participantType = fieldSetFlags()[2] ? this.participantType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.firstName = fieldSetFlags()[3] ? this.firstName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.lastName = fieldSetFlags()[4] ? this.lastName : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.middleName = fieldSetFlags()[5] ? this.middleName : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.noMiddleName = fieldSetFlags()[6] ? this.noMiddleName : (java.lang.Boolean) defaultValue(fields()[6]);
        record.dob = fieldSetFlags()[7] ? this.dob : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.companyName = fieldSetFlags()[8] ? this.companyName : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.addressType = fieldSetFlags()[9] ? this.addressType : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.streetNumber = fieldSetFlags()[10] ? this.streetNumber : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.streetName = fieldSetFlags()[11] ? this.streetName : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.streetUnit = fieldSetFlags()[12] ? this.streetUnit : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.city = fieldSetFlags()[13] ? this.city : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.state = fieldSetFlags()[14] ? this.state : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.postalCode = fieldSetFlags()[15] ? this.postalCode : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.emailAddress = fieldSetFlags()[16] ? this.emailAddress : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.phoneType = fieldSetFlags()[17] ? this.phoneType : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.phoneNumber = fieldSetFlags()[18] ? this.phoneNumber : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.licenseNumber = fieldSetFlags()[19] ? this.licenseNumber : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.licenseState = fieldSetFlags()[20] ? this.licenseState : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.licenseType = fieldSetFlags()[21] ? this.licenseType : (java.lang.CharSequence) defaultValue(fields()[21]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PartyMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<PartyMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PartyMessage>
    READER$ = (org.apache.avro.io.DatumReader<PartyMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.partyId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.partyId);
    }

    if (this.partyType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.partyType);
    }

    if (this.participantType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.participantType);
    }

    if (this.firstName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.firstName);
    }

    if (this.lastName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lastName);
    }

    if (this.middleName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.middleName);
    }

    if (this.noMiddleName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeBoolean(this.noMiddleName);
    }

    if (this.dob == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.dob);
    }

    if (this.companyName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.companyName);
    }

    if (this.addressType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.addressType);
    }

    if (this.streetNumber == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.streetNumber);
    }

    if (this.streetName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.streetName);
    }

    if (this.streetUnit == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.streetUnit);
    }

    if (this.city == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.city);
    }

    if (this.state == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.state);
    }

    if (this.postalCode == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.postalCode);
    }

    if (this.emailAddress == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.emailAddress);
    }

    if (this.phoneType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.phoneType);
    }

    if (this.phoneNumber == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.phoneNumber);
    }

    if (this.licenseNumber == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.licenseNumber);
    }

    if (this.licenseState == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.licenseState);
    }

    if (this.licenseType == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.licenseType);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.partyId = null;
      } else {
        this.partyId = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.partyType = null;
      } else {
        this.partyType = in.readString(this.partyType instanceof Utf8 ? (Utf8)this.partyType : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.participantType = null;
      } else {
        this.participantType = in.readString(this.participantType instanceof Utf8 ? (Utf8)this.participantType : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.firstName = null;
      } else {
        this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lastName = null;
      } else {
        this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.middleName = null;
      } else {
        this.middleName = in.readString(this.middleName instanceof Utf8 ? (Utf8)this.middleName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.noMiddleName = null;
      } else {
        this.noMiddleName = in.readBoolean();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.dob = null;
      } else {
        this.dob = in.readString(this.dob instanceof Utf8 ? (Utf8)this.dob : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.companyName = null;
      } else {
        this.companyName = in.readString(this.companyName instanceof Utf8 ? (Utf8)this.companyName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.addressType = null;
      } else {
        this.addressType = in.readString(this.addressType instanceof Utf8 ? (Utf8)this.addressType : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.streetNumber = null;
      } else {
        this.streetNumber = in.readString(this.streetNumber instanceof Utf8 ? (Utf8)this.streetNumber : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.streetName = null;
      } else {
        this.streetName = in.readString(this.streetName instanceof Utf8 ? (Utf8)this.streetName : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.streetUnit = null;
      } else {
        this.streetUnit = in.readString(this.streetUnit instanceof Utf8 ? (Utf8)this.streetUnit : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.city = null;
      } else {
        this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.state = null;
      } else {
        this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.postalCode = null;
      } else {
        this.postalCode = in.readString(this.postalCode instanceof Utf8 ? (Utf8)this.postalCode : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.emailAddress = null;
      } else {
        this.emailAddress = in.readString(this.emailAddress instanceof Utf8 ? (Utf8)this.emailAddress : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.phoneType = null;
      } else {
        this.phoneType = in.readString(this.phoneType instanceof Utf8 ? (Utf8)this.phoneType : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.phoneNumber = null;
      } else {
        this.phoneNumber = in.readString(this.phoneNumber instanceof Utf8 ? (Utf8)this.phoneNumber : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.licenseNumber = null;
      } else {
        this.licenseNumber = in.readString(this.licenseNumber instanceof Utf8 ? (Utf8)this.licenseNumber : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.licenseState = null;
      } else {
        this.licenseState = in.readString(this.licenseState instanceof Utf8 ? (Utf8)this.licenseState : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.licenseType = null;
      } else {
        this.licenseType = in.readString(this.licenseType instanceof Utf8 ? (Utf8)this.licenseType : null);
      }

    } else {
      for (int i = 0; i < 22; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.partyId = null;
          } else {
            this.partyId = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.partyType = null;
          } else {
            this.partyType = in.readString(this.partyType instanceof Utf8 ? (Utf8)this.partyType : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.participantType = null;
          } else {
            this.participantType = in.readString(this.participantType instanceof Utf8 ? (Utf8)this.participantType : null);
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.firstName = null;
          } else {
            this.firstName = in.readString(this.firstName instanceof Utf8 ? (Utf8)this.firstName : null);
          }
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lastName = null;
          } else {
            this.lastName = in.readString(this.lastName instanceof Utf8 ? (Utf8)this.lastName : null);
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.middleName = null;
          } else {
            this.middleName = in.readString(this.middleName instanceof Utf8 ? (Utf8)this.middleName : null);
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.noMiddleName = null;
          } else {
            this.noMiddleName = in.readBoolean();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.dob = null;
          } else {
            this.dob = in.readString(this.dob instanceof Utf8 ? (Utf8)this.dob : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.companyName = null;
          } else {
            this.companyName = in.readString(this.companyName instanceof Utf8 ? (Utf8)this.companyName : null);
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.addressType = null;
          } else {
            this.addressType = in.readString(this.addressType instanceof Utf8 ? (Utf8)this.addressType : null);
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.streetNumber = null;
          } else {
            this.streetNumber = in.readString(this.streetNumber instanceof Utf8 ? (Utf8)this.streetNumber : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.streetName = null;
          } else {
            this.streetName = in.readString(this.streetName instanceof Utf8 ? (Utf8)this.streetName : null);
          }
          break;

        case 12:
          if (in.readIndex() != 1) {
            in.readNull();
            this.streetUnit = null;
          } else {
            this.streetUnit = in.readString(this.streetUnit instanceof Utf8 ? (Utf8)this.streetUnit : null);
          }
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.city = null;
          } else {
            this.city = in.readString(this.city instanceof Utf8 ? (Utf8)this.city : null);
          }
          break;

        case 14:
          if (in.readIndex() != 1) {
            in.readNull();
            this.state = null;
          } else {
            this.state = in.readString(this.state instanceof Utf8 ? (Utf8)this.state : null);
          }
          break;

        case 15:
          if (in.readIndex() != 1) {
            in.readNull();
            this.postalCode = null;
          } else {
            this.postalCode = in.readString(this.postalCode instanceof Utf8 ? (Utf8)this.postalCode : null);
          }
          break;

        case 16:
          if (in.readIndex() != 1) {
            in.readNull();
            this.emailAddress = null;
          } else {
            this.emailAddress = in.readString(this.emailAddress instanceof Utf8 ? (Utf8)this.emailAddress : null);
          }
          break;

        case 17:
          if (in.readIndex() != 1) {
            in.readNull();
            this.phoneType = null;
          } else {
            this.phoneType = in.readString(this.phoneType instanceof Utf8 ? (Utf8)this.phoneType : null);
          }
          break;

        case 18:
          if (in.readIndex() != 1) {
            in.readNull();
            this.phoneNumber = null;
          } else {
            this.phoneNumber = in.readString(this.phoneNumber instanceof Utf8 ? (Utf8)this.phoneNumber : null);
          }
          break;

        case 19:
          if (in.readIndex() != 1) {
            in.readNull();
            this.licenseNumber = null;
          } else {
            this.licenseNumber = in.readString(this.licenseNumber instanceof Utf8 ? (Utf8)this.licenseNumber : null);
          }
          break;

        case 20:
          if (in.readIndex() != 1) {
            in.readNull();
            this.licenseState = null;
          } else {
            this.licenseState = in.readString(this.licenseState instanceof Utf8 ? (Utf8)this.licenseState : null);
          }
          break;

        case 21:
          if (in.readIndex() != 1) {
            in.readNull();
            this.licenseType = null;
          } else {
            this.licenseType = in.readString(this.licenseType instanceof Utf8 ? (Utf8)this.licenseType : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










