/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.auction.sfdc.contract.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ContractPayload extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8761511619747162L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContractPayload\",\"namespace\":\"com.auction.sfdc.contract.avro\",\"fields\":[{\"name\":\"created_date\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"updated_date\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"created_by\",\"type\":\"int\"},{\"name\":\"updated_by\",\"type\":\"int\"},{\"name\":\"contract_id\",\"type\":\"int\"},{\"name\":\"offer_id\",\"type\":\"int\"},{\"name\":\"listing_id\",\"type\":\"int\"},{\"name\":\"mlh_contract_id\",\"type\":\"int\"},{\"name\":\"media\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"media_record\",\"fields\":[{\"name\":\"created_date\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"updated_date\",\"type\":\"int\",\"logicalType\":\"date\"},{\"name\":\"created_by\",\"type\":\"int\"},{\"name\":\"updated_by\",\"type\":\"int\"},{\"name\":\"media_id\",\"type\":\"int\"},{\"name\":\"media_uri\",\"type\":\"string\"},{\"name\":\"download_uri\",\"type\":\"string\"},{\"name\":\"internal_title\",\"type\":\"string\"},{\"name\":\"file_name\",\"type\":\"string\"},{\"name\":\"content_type\",\"type\":\"string\"},{\"name\":\"media_type\",\"type\":\"string\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContractPayload> ENCODER =
      new BinaryMessageEncoder<ContractPayload>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContractPayload> DECODER =
      new BinaryMessageDecoder<ContractPayload>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ContractPayload> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ContractPayload> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ContractPayload> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContractPayload>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ContractPayload to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ContractPayload from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ContractPayload instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ContractPayload fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int created_date;
   private int updated_date;
   private int created_by;
   private int updated_by;
   private int contract_id;
   private int offer_id;
   private int listing_id;
   private int mlh_contract_id;
   private java.util.List<com.auction.sfdc.contract.avro.media_record> media;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContractPayload() {}

  /**
   * All-args constructor.
   * @param created_date The new value for created_date
   * @param updated_date The new value for updated_date
   * @param created_by The new value for created_by
   * @param updated_by The new value for updated_by
   * @param contract_id The new value for contract_id
   * @param offer_id The new value for offer_id
   * @param listing_id The new value for listing_id
   * @param mlh_contract_id The new value for mlh_contract_id
   * @param media The new value for media
   */
  public ContractPayload(java.lang.Integer created_date, java.lang.Integer updated_date, java.lang.Integer created_by, java.lang.Integer updated_by, java.lang.Integer contract_id, java.lang.Integer offer_id, java.lang.Integer listing_id, java.lang.Integer mlh_contract_id, java.util.List<com.auction.sfdc.contract.avro.media_record> media) {
    this.created_date = created_date;
    this.updated_date = updated_date;
    this.created_by = created_by;
    this.updated_by = updated_by;
    this.contract_id = contract_id;
    this.offer_id = offer_id;
    this.listing_id = listing_id;
    this.mlh_contract_id = mlh_contract_id;
    this.media = media;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return created_date;
    case 1: return updated_date;
    case 2: return created_by;
    case 3: return updated_by;
    case 4: return contract_id;
    case 5: return offer_id;
    case 6: return listing_id;
    case 7: return mlh_contract_id;
    case 8: return media;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: created_date = (java.lang.Integer)value$; break;
    case 1: updated_date = (java.lang.Integer)value$; break;
    case 2: created_by = (java.lang.Integer)value$; break;
    case 3: updated_by = (java.lang.Integer)value$; break;
    case 4: contract_id = (java.lang.Integer)value$; break;
    case 5: offer_id = (java.lang.Integer)value$; break;
    case 6: listing_id = (java.lang.Integer)value$; break;
    case 7: mlh_contract_id = (java.lang.Integer)value$; break;
    case 8: media = (java.util.List<com.auction.sfdc.contract.avro.media_record>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'created_date' field.
   * @return The value of the 'created_date' field.
   */
  public int getCreatedDate() {
    return created_date;
  }


  /**
   * Sets the value of the 'created_date' field.
   * @param value the value to set.
   */
  public void setCreatedDate(int value) {
    this.created_date = value;
  }

  /**
   * Gets the value of the 'updated_date' field.
   * @return The value of the 'updated_date' field.
   */
  public int getUpdatedDate() {
    return updated_date;
  }


  /**
   * Sets the value of the 'updated_date' field.
   * @param value the value to set.
   */
  public void setUpdatedDate(int value) {
    this.updated_date = value;
  }

  /**
   * Gets the value of the 'created_by' field.
   * @return The value of the 'created_by' field.
   */
  public int getCreatedBy() {
    return created_by;
  }


  /**
   * Sets the value of the 'created_by' field.
   * @param value the value to set.
   */
  public void setCreatedBy(int value) {
    this.created_by = value;
  }

  /**
   * Gets the value of the 'updated_by' field.
   * @return The value of the 'updated_by' field.
   */
  public int getUpdatedBy() {
    return updated_by;
  }


  /**
   * Sets the value of the 'updated_by' field.
   * @param value the value to set.
   */
  public void setUpdatedBy(int value) {
    this.updated_by = value;
  }

  /**
   * Gets the value of the 'contract_id' field.
   * @return The value of the 'contract_id' field.
   */
  public int getContractId() {
    return contract_id;
  }


  /**
   * Sets the value of the 'contract_id' field.
   * @param value the value to set.
   */
  public void setContractId(int value) {
    this.contract_id = value;
  }

  /**
   * Gets the value of the 'offer_id' field.
   * @return The value of the 'offer_id' field.
   */
  public int getOfferId() {
    return offer_id;
  }


  /**
   * Sets the value of the 'offer_id' field.
   * @param value the value to set.
   */
  public void setOfferId(int value) {
    this.offer_id = value;
  }

  /**
   * Gets the value of the 'listing_id' field.
   * @return The value of the 'listing_id' field.
   */
  public int getListingId() {
    return listing_id;
  }


  /**
   * Sets the value of the 'listing_id' field.
   * @param value the value to set.
   */
  public void setListingId(int value) {
    this.listing_id = value;
  }

  /**
   * Gets the value of the 'mlh_contract_id' field.
   * @return The value of the 'mlh_contract_id' field.
   */
  public int getMlhContractId() {
    return mlh_contract_id;
  }


  /**
   * Sets the value of the 'mlh_contract_id' field.
   * @param value the value to set.
   */
  public void setMlhContractId(int value) {
    this.mlh_contract_id = value;
  }

  /**
   * Gets the value of the 'media' field.
   * @return The value of the 'media' field.
   */
  public java.util.List<com.auction.sfdc.contract.avro.media_record> getMedia() {
    return media;
  }


  /**
   * Sets the value of the 'media' field.
   * @param value the value to set.
   */
  public void setMedia(java.util.List<com.auction.sfdc.contract.avro.media_record> value) {
    this.media = value;
  }

  /**
   * Creates a new ContractPayload RecordBuilder.
   * @return A new ContractPayload RecordBuilder
   */
  public static com.auction.sfdc.contract.avro.ContractPayload.Builder newBuilder() {
    return new com.auction.sfdc.contract.avro.ContractPayload.Builder();
  }

  /**
   * Creates a new ContractPayload RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContractPayload RecordBuilder
   */
  public static com.auction.sfdc.contract.avro.ContractPayload.Builder newBuilder(com.auction.sfdc.contract.avro.ContractPayload.Builder other) {
    if (other == null) {
      return new com.auction.sfdc.contract.avro.ContractPayload.Builder();
    } else {
      return new com.auction.sfdc.contract.avro.ContractPayload.Builder(other);
    }
  }

  /**
   * Creates a new ContractPayload RecordBuilder by copying an existing ContractPayload instance.
   * @param other The existing instance to copy.
   * @return A new ContractPayload RecordBuilder
   */
  public static com.auction.sfdc.contract.avro.ContractPayload.Builder newBuilder(com.auction.sfdc.contract.avro.ContractPayload other) {
    if (other == null) {
      return new com.auction.sfdc.contract.avro.ContractPayload.Builder();
    } else {
      return new com.auction.sfdc.contract.avro.ContractPayload.Builder(other);
    }
  }

  /**
   * RecordBuilder for ContractPayload instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContractPayload>
    implements org.apache.avro.data.RecordBuilder<ContractPayload> {

    private int created_date;
    private int updated_date;
    private int created_by;
    private int updated_by;
    private int contract_id;
    private int offer_id;
    private int listing_id;
    private int mlh_contract_id;
    private java.util.List<com.auction.sfdc.contract.avro.media_record> media;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.auction.sfdc.contract.avro.ContractPayload.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.created_date)) {
        this.created_date = data().deepCopy(fields()[0].schema(), other.created_date);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.updated_date)) {
        this.updated_date = data().deepCopy(fields()[1].schema(), other.updated_date);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.created_by)) {
        this.created_by = data().deepCopy(fields()[2].schema(), other.created_by);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.updated_by)) {
        this.updated_by = data().deepCopy(fields()[3].schema(), other.updated_by);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.contract_id)) {
        this.contract_id = data().deepCopy(fields()[4].schema(), other.contract_id);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.offer_id)) {
        this.offer_id = data().deepCopy(fields()[5].schema(), other.offer_id);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.listing_id)) {
        this.listing_id = data().deepCopy(fields()[6].schema(), other.listing_id);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.mlh_contract_id)) {
        this.mlh_contract_id = data().deepCopy(fields()[7].schema(), other.mlh_contract_id);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.media)) {
        this.media = data().deepCopy(fields()[8].schema(), other.media);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing ContractPayload instance
     * @param other The existing instance to copy.
     */
    private Builder(com.auction.sfdc.contract.avro.ContractPayload other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.created_date)) {
        this.created_date = data().deepCopy(fields()[0].schema(), other.created_date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.updated_date)) {
        this.updated_date = data().deepCopy(fields()[1].schema(), other.updated_date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.created_by)) {
        this.created_by = data().deepCopy(fields()[2].schema(), other.created_by);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.updated_by)) {
        this.updated_by = data().deepCopy(fields()[3].schema(), other.updated_by);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.contract_id)) {
        this.contract_id = data().deepCopy(fields()[4].schema(), other.contract_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.offer_id)) {
        this.offer_id = data().deepCopy(fields()[5].schema(), other.offer_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.listing_id)) {
        this.listing_id = data().deepCopy(fields()[6].schema(), other.listing_id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.mlh_contract_id)) {
        this.mlh_contract_id = data().deepCopy(fields()[7].schema(), other.mlh_contract_id);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.media)) {
        this.media = data().deepCopy(fields()[8].schema(), other.media);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'created_date' field.
      * @return The value.
      */
    public int getCreatedDate() {
      return created_date;
    }


    /**
      * Sets the value of the 'created_date' field.
      * @param value The value of 'created_date'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setCreatedDate(int value) {
      validate(fields()[0], value);
      this.created_date = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'created_date' field has been set.
      * @return True if the 'created_date' field has been set, false otherwise.
      */
    public boolean hasCreatedDate() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'created_date' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearCreatedDate() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'updated_date' field.
      * @return The value.
      */
    public int getUpdatedDate() {
      return updated_date;
    }


    /**
      * Sets the value of the 'updated_date' field.
      * @param value The value of 'updated_date'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setUpdatedDate(int value) {
      validate(fields()[1], value);
      this.updated_date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'updated_date' field has been set.
      * @return True if the 'updated_date' field has been set, false otherwise.
      */
    public boolean hasUpdatedDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'updated_date' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearUpdatedDate() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_by' field.
      * @return The value.
      */
    public int getCreatedBy() {
      return created_by;
    }


    /**
      * Sets the value of the 'created_by' field.
      * @param value The value of 'created_by'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setCreatedBy(int value) {
      validate(fields()[2], value);
      this.created_by = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'created_by' field has been set.
      * @return True if the 'created_by' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'created_by' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearCreatedBy() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'updated_by' field.
      * @return The value.
      */
    public int getUpdatedBy() {
      return updated_by;
    }


    /**
      * Sets the value of the 'updated_by' field.
      * @param value The value of 'updated_by'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setUpdatedBy(int value) {
      validate(fields()[3], value);
      this.updated_by = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'updated_by' field has been set.
      * @return True if the 'updated_by' field has been set, false otherwise.
      */
    public boolean hasUpdatedBy() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'updated_by' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearUpdatedBy() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'contract_id' field.
      * @return The value.
      */
    public int getContractId() {
      return contract_id;
    }


    /**
      * Sets the value of the 'contract_id' field.
      * @param value The value of 'contract_id'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setContractId(int value) {
      validate(fields()[4], value);
      this.contract_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'contract_id' field has been set.
      * @return True if the 'contract_id' field has been set, false otherwise.
      */
    public boolean hasContractId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'contract_id' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearContractId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'offer_id' field.
      * @return The value.
      */
    public int getOfferId() {
      return offer_id;
    }


    /**
      * Sets the value of the 'offer_id' field.
      * @param value The value of 'offer_id'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setOfferId(int value) {
      validate(fields()[5], value);
      this.offer_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'offer_id' field has been set.
      * @return True if the 'offer_id' field has been set, false otherwise.
      */
    public boolean hasOfferId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'offer_id' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearOfferId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'listing_id' field.
      * @return The value.
      */
    public int getListingId() {
      return listing_id;
    }


    /**
      * Sets the value of the 'listing_id' field.
      * @param value The value of 'listing_id'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setListingId(int value) {
      validate(fields()[6], value);
      this.listing_id = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'listing_id' field has been set.
      * @return True if the 'listing_id' field has been set, false otherwise.
      */
    public boolean hasListingId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'listing_id' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearListingId() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'mlh_contract_id' field.
      * @return The value.
      */
    public int getMlhContractId() {
      return mlh_contract_id;
    }


    /**
      * Sets the value of the 'mlh_contract_id' field.
      * @param value The value of 'mlh_contract_id'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setMlhContractId(int value) {
      validate(fields()[7], value);
      this.mlh_contract_id = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'mlh_contract_id' field has been set.
      * @return True if the 'mlh_contract_id' field has been set, false otherwise.
      */
    public boolean hasMlhContractId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'mlh_contract_id' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearMlhContractId() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'media' field.
      * @return The value.
      */
    public java.util.List<com.auction.sfdc.contract.avro.media_record> getMedia() {
      return media;
    }


    /**
      * Sets the value of the 'media' field.
      * @param value The value of 'media'.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder setMedia(java.util.List<com.auction.sfdc.contract.avro.media_record> value) {
      validate(fields()[8], value);
      this.media = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'media' field has been set.
      * @return True if the 'media' field has been set, false otherwise.
      */
    public boolean hasMedia() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'media' field.
      * @return This builder.
      */
    public com.auction.sfdc.contract.avro.ContractPayload.Builder clearMedia() {
      media = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContractPayload build() {
      try {
        ContractPayload record = new ContractPayload();
        record.created_date = fieldSetFlags()[0] ? this.created_date : (java.lang.Integer) defaultValue(fields()[0]);
        record.updated_date = fieldSetFlags()[1] ? this.updated_date : (java.lang.Integer) defaultValue(fields()[1]);
        record.created_by = fieldSetFlags()[2] ? this.created_by : (java.lang.Integer) defaultValue(fields()[2]);
        record.updated_by = fieldSetFlags()[3] ? this.updated_by : (java.lang.Integer) defaultValue(fields()[3]);
        record.contract_id = fieldSetFlags()[4] ? this.contract_id : (java.lang.Integer) defaultValue(fields()[4]);
        record.offer_id = fieldSetFlags()[5] ? this.offer_id : (java.lang.Integer) defaultValue(fields()[5]);
        record.listing_id = fieldSetFlags()[6] ? this.listing_id : (java.lang.Integer) defaultValue(fields()[6]);
        record.mlh_contract_id = fieldSetFlags()[7] ? this.mlh_contract_id : (java.lang.Integer) defaultValue(fields()[7]);
        record.media = fieldSetFlags()[8] ? this.media : (java.util.List<com.auction.sfdc.contract.avro.media_record>) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContractPayload>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContractPayload>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContractPayload>
    READER$ = (org.apache.avro.io.DatumReader<ContractPayload>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.created_date);

    out.writeInt(this.updated_date);

    out.writeInt(this.created_by);

    out.writeInt(this.updated_by);

    out.writeInt(this.contract_id);

    out.writeInt(this.offer_id);

    out.writeInt(this.listing_id);

    out.writeInt(this.mlh_contract_id);

    long size0 = this.media.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.auction.sfdc.contract.avro.media_record e0: this.media) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.created_date = in.readInt();

      this.updated_date = in.readInt();

      this.created_by = in.readInt();

      this.updated_by = in.readInt();

      this.contract_id = in.readInt();

      this.offer_id = in.readInt();

      this.listing_id = in.readInt();

      this.mlh_contract_id = in.readInt();

      long size0 = in.readArrayStart();
      java.util.List<com.auction.sfdc.contract.avro.media_record> a0 = this.media;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.auction.sfdc.contract.avro.media_record>((int)size0, SCHEMA$.getField("media").schema());
        this.media = a0;
      } else a0.clear();
      SpecificData.Array<com.auction.sfdc.contract.avro.media_record> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.auction.sfdc.contract.avro.media_record>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.auction.sfdc.contract.avro.media_record e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.auction.sfdc.contract.avro.media_record();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.created_date = in.readInt();
          break;

        case 1:
          this.updated_date = in.readInt();
          break;

        case 2:
          this.created_by = in.readInt();
          break;

        case 3:
          this.updated_by = in.readInt();
          break;

        case 4:
          this.contract_id = in.readInt();
          break;

        case 5:
          this.offer_id = in.readInt();
          break;

        case 6:
          this.listing_id = in.readInt();
          break;

        case 7:
          this.mlh_contract_id = in.readInt();
          break;

        case 8:
          long size0 = in.readArrayStart();
          java.util.List<com.auction.sfdc.contract.avro.media_record> a0 = this.media;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.auction.sfdc.contract.avro.media_record>((int)size0, SCHEMA$.getField("media").schema());
            this.media = a0;
          } else a0.clear();
          SpecificData.Array<com.auction.sfdc.contract.avro.media_record> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.auction.sfdc.contract.avro.media_record>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.auction.sfdc.contract.avro.media_record e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.auction.sfdc.contract.avro.media_record();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










